collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.04530407954007387
  brandStrength: 0.3824274558573961
  rhythmicContrast: 0.8524452573619783
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  lightness: 0.1204218715429306
typography_spectrum: 0.6491228
layout_spectrum: 1
name: everydaydream
